# Generated by Django 5.1.3 on 2024-11-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('em_music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='songs/media'),
        ),
    ]
