# Generated by Django 5.1.3 on 2024-12-02 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("em_music", "0003_song_favorited_by_playhistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("artist", models.CharField(max_length=255)),
                ("album", models.CharField(max_length=255)),
                ("genre", models.CharField(max_length=100)),
                ("release_date", models.DateField()),
                ("file_url", models.URLField()),
                ("plays", models.PositiveIntegerField(default=0)),
                ("duration", models.IntegerField()),
                ("description", models.TextField(blank=True, null=True)),
                ("lyrics", models.TextField(blank=True, null=True)),
                (
                    "song",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="track",
                        to="em_music.song",
                    ),
                ),
            ],
        ),
    ]
